import type { Config } from 'tailwindcss';

const config: Config = {
    darkMode: ['class'],
    content: ['./index.html', './src/**/*.{ts,tsx}'],
    theme: {
        extend: {
            fontFamily: {
                "code-sm": ["JetBrains Mono", "monospace"],
                "label-caps": ["JetBrains Mono", "monospace"],
                "display-xl": ["Inter", "sans-serif"],
                "body-md": ["Inter", "sans-serif"],
                "code-lg": ["JetBrains Mono", "monospace"],
                "headline-lg": ["Inter", "sans-serif"],
                "code-md": ["JetBrains Mono", "monospace"]
            },
            fontSize: {
                "code-sm": ["12px", { "lineHeight": "1.4", "fontWeight": "400" }],
                "label-caps": ["10px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700" }],
                "display-xl": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "body-md": ["14px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "code-lg": ["16px", { "lineHeight": "1.5", "fontWeight": "500" }],
                "headline-lg": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "code-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }]
            },
            colors: {
                "surface-tint": "#c1c1ff",
                "on-secondary": "#302e45",
                "secondary-fixed": "#e4dffe",
                "secondary-container": "#46445d",
                "on-secondary-fixed-variant": "#46445d",
                "on-primary-container": "#110095",
                "on-surface": "#e2e2e2",
                "secondary": "#c8c3e1",
                "surface-dim": "#121414",
                "tertiary-fixed": "#ffdbc8",
                "tertiary": "#ffb689",
                "secondary-fixed-dim": "#c8c3e1",
                "on-tertiary-fixed": "#311300",
                "inverse-primary": "#4846e3",
                "surface-container-high": "#282a2b",
                "on-background": "#e2e2e2",
                "on-error-container": "#ffdad6",
                "tertiary-container": "#df731f",
                "primary-container": "#8183ff",
                "on-tertiary-fixed-variant": "#743500",
                "on-primary-fixed-variant": "#2d25cc",
                "surface-bright": "#37393a",
                "surface-container-highest": "#333535",
                "primary": "#c1c1ff",
                "on-secondary-container": "#b6b2d0",
                "background": "#121414",
                "outline-variant": "#464555",
                "inverse-surface": "#e2e2e2",
                "error": "#ffb4ab",
                "surface-variant": "#333535",
                "surface": "#121414",
                "on-error": "#690005",
                "on-primary-fixed": "#09006b",
                "on-tertiary-container": "#471e00",
                "primary-fixed": "#e1dfff",
                "on-primary": "#1500a8",
                "error-container": "#93000a",
                "on-secondary-fixed": "#1b192f",
                "surface-container-low": "#1a1c1c",
                "on-surface-variant": "#c7c4d8",
                "surface-container": "#1e2020",
                "outline": "#908fa1",
                "primary-fixed-dim": "#c1c1ff",
                "on-tertiary": "#512300",
                "tertiary-fixed-dim": "#ffb689",
                "inverse-on-surface": "#2f3131",
                "surface-container-lowest": "#0c0f0f",
                "thread-border": "rgba(255,255,255,0.1)",
                "thread-dim": "rgba(255,255,255,0.05)",
                "thread-active": "#8183ff"
            },
        },
    },
    plugins: [],
};

export default config;
